"""Initial migration.

Revision ID: 1d8fc4eafbcc
Revises: 
Create Date: 2024-06-02 15:25:10.301809

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1d8fc4eafbcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pedido')
    op.drop_table('produto')
    op.drop_table('carrinho')
    op.drop_table('pagamento')
    op.drop_table('categoria')
    op.drop_table('entrega')
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('has_ativo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('data_cadastro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    with op.batch_alter_table('vendedor', schema=None) as batch_op:
        batch_op.alter_column('cpnj',
               existing_type=mysql.VARCHAR(length=14),
               nullable=False)
        batch_op.alter_column('has_ativo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=True,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('data_cadastro',
               existing_type=mysql.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendedor', schema=None) as batch_op:
        batch_op.alter_column('data_cadastro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('has_ativo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))
        batch_op.alter_column('cpnj',
               existing_type=mysql.VARCHAR(length=14),
               nullable=True)

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('data_cadastro',
               existing_type=sa.DateTime(),
               type_=mysql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('CURRENT_TIMESTAMP'))
        batch_op.alter_column('has_ativo',
               existing_type=mysql.TINYINT(display_width=1),
               nullable=False,
               existing_server_default=sa.text("'1'"))

    op.create_table('entrega',
    sa.Column('id_entrega', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('has_entrega', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('fk_id_pagamento', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('has_ativo', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('data_inicio', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('data_entrega', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['fk_id_pagamento'], ['pagamento.id_pagamento'], name='entrega_ibfk_1'),
    sa.PrimaryKeyConstraint('id_entrega'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('categoria',
    sa.Column('id_categoria', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('has_ativo', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id_categoria'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pagamento',
    sa.Column('id_pagamento', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('has_pagamento', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('fk_id_pedido', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('has_ativo', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('data_pagamento', mysql.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['fk_id_pedido'], ['pedido.id_pedido'], name='pagamento_ibfk_1'),
    sa.PrimaryKeyConstraint('id_pagamento'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('carrinho',
    sa.Column('id_carrinho', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('fk_id_produto', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fk_id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('has_ativo', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fk_id_produto'], ['produto.id_produto'], name='carrinho_ibfk_1'),
    sa.ForeignKeyConstraint(['fk_id_usuario'], ['usuario.id_usuario'], name='carrinho_ibfk_2'),
    sa.PrimaryKeyConstraint('id_carrinho'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('produto',
    sa.Column('id_produto', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('preco', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estoque', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('fk_id_categoria', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fk_id_vendedor', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('has_ativo', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['fk_id_categoria'], ['categoria.id_categoria'], name='produto_ibfk_1'),
    sa.ForeignKeyConstraint(['fk_id_vendedor'], ['vendedor.id_vendedor'], name='produto_ibfk_2'),
    sa.PrimaryKeyConstraint('id_produto'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('pedido',
    sa.Column('id_pedido', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('quantidade', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fk_id_usuario', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('fk_id_produto', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('data_criacao', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('has_ativo', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['fk_id_produto'], ['produto.id_produto'], name='pedido_ibfk_2'),
    sa.ForeignKeyConstraint(['fk_id_usuario'], ['usuario.id_usuario'], name='pedido_ibfk_1'),
    sa.PrimaryKeyConstraint('id_pedido'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
